# -*- coding: utf-8 -*-
"""geolocation_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lb0hoPf3oAK57V8uE97sI7He5DS1PZdm
"""

# geolocation_model.py
from geopy.geocoders import Nominatim

class GeolocationModel:
    def __init__(self):
        self.geolocator = Nominatim(user_agent="health_assistant")

    def get_geolocation(self, location):
        """
        Get latitude and longitude for a given location using Geopy Nominatim API.
        """
        try:
            location = self.geolocator.geocode(location)
            if location:
                return location.latitude, location.longitude
            else:
                return None, None
        except Exception as e:
            return None, None