# -*- coding: utf-8 -*-
"""geolocation_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lb0hoPf3oAK57V8uE97sI7He5DS1PZdm
"""
# nearby_services_model.py
import requests
import os 

class NearbyServicesModel:
    def __init__(self, api_key):
        self.api_key = api_key

    def get_nearby_services(self, lat, lng):
        """
        Fetch dynamic nearby medical services using HERE Places API.
        """
        url = "https://discover.search.hereapi.com/v1/discover"

        # Fetch the API key from the environment variables (if needed)
        api_key = os.getenv("HERE_API_KEY", self.api_key)

        # Define the parameters correctly
        params = {
            "q": "hospital",  # Search term (hospital)
            "at": f"{lat},{lng}",  # Latitude, Longitude
            "limit": 10,  # Limit results
            "apiKey": api_key  # Correct API key placement
        }

        # Send the GET request
        response = requests.get(url, params=params)

        # Parse the response
        if response.status_code == 200:
            data = response.json()
            if "items" in data and data["items"]:
                print(f"Nearby medical services in the area:")
                for place in data["items"]:
                    name = place.get('title', 'No name available')
                    address = place.get('address', {}).get('label', 'No address available')
                    print(f"Name: {name}")
                    print(f"Address: {address}")
                    print("-" * 50)  # Separator for clarity
            else:
                print("No nearby services found.")
        else:
            print(f"Error: {response.status_code}, {response.text}")
